name: KICS

on:
  workflow_dispatch: #for testing
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  kics-job:
    runs-on: ubuntu-latest
    name: kics-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Mkdir results-dir
        # make sure results dir is created
        run: mkdir -p results-dir
      - name: Run KICS Scan with SARIF result
        uses: checkmarx/kics-github-action@v1.6
        with:
          path: 'terraform'
          output_path: results-dir
          platform_type: terraform
          output_formats: 'sarif'
          ignore_on_exit: results
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results-dir/results.sarif
